Poses mapped
niwcpac/mole pull request #7
Opened 2022-08-01 22:09 UTC by ndan029

plot poses by pose source (different hard-coded color per pose source)
update our custom pose angular model to include an id
add "id_gt" filter to pose api endpoinnt
create pose api angular service (recursively retrieve poses with optional trial and optional id_gt parameter)

2022-08-06 00:55 UTC, supr3m3 requested changes

2022-08-06 00:55 UTC, hohumsup commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +          let asdf = {
rename asdf to something more explicit so we know what this variable is used for

2022-08-06 00:55 UTC, hohumsup commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +let COLORS = [
thoughts on adding something to similar to `point_style` on` event_types` to `pose_source`? so we can avoid hardcoded colors and any other potential styling changes in the future like shape and color

2022-08-06 00:55 UTC, hohumsup commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +    }, this);
some poses disappear whenever there's a new pose. however, refreshing the page will display all the poses again.

see below

before (on a refresh)
![before_pose](https://user-images.githubusercontent.com/45615840/183223893-27b5b1fc-c4bf-41ba-ad31-91edcfde30e8.png)

after (a new pose  was posted to the endpoint)
![after_pose](https://user-images.githubusercontent.com/45615840/183223891-207359e7-2dd8-4a40-9b12-4b2aea435fde.png)

in addition to mission poses, the ship icon should be on the furthest right dot but it doesn't get displayed properly unless the page gets refreshed

- [x] fix disappearing poses

2022-08-06 00:55 UTC, hohumsup commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +      this.loadPosesSource(changes.posesByPoseSource.currentValue);
here are more info on disappearing poses. below is the output of `changes.posesByPoseSource.currentValue`. it seems like some entity from the pose source gets dropped?

before (on a refresh)
```
GPS: {usv1: Array(6), target_usv: Array(5), map_marker: Array(3)}
Reported: {target_usv: Array(2), map_marker: Array(1), usv1: Array(1)}
```
after (a new pose was posted to the endpoint)
```
GPS: {usv1: Array(7)}
Reported: {target_usv: Array(2), map_marker: Array(1), usv1: Array(1)}
```

2022-08-06 00:55 UTC, supr3m3 commented on angular/app/src/app/shared/components/maps/maps.component.ts
> +              new_list =  [...this.posesByPoseSource[pose_source][entity], ...many_poses[pose_source][entity]];
i think this is where some poses get dropped when there's a new pose

2022-08-06 00:55 UTC, supr3m3 commented on angular/app/src/app/shared/services/map/pose-api.service.ts
> +  catagorizePoses(page: PosePageResult) {
```suggestion
  categorizePoses(page: PosePageResult) {
```

2022-08-06 00:55 UTC, supr3m3 commented on angular/app/src/app/shared/services/map/pose-api.service.ts
> +    this.recursiveSubscription = posesRequest.subscribe(this.catagorizePoses.bind(this));
```suggestion
    this.recursiveSubscription = posesRequest.subscribe(this.categorizePoses.bind(this));
```

2022-08-06 00:55 UTC, supr3m3 commented on angular/app/src/app/shared/services/map/pose-api.service.ts
> +    this.recursiveSubscription = posesRequest.subscribe(this.catagorizePoses.bind(this));
```suggestion
    this.recursiveSubscription = posesRequest.subscribe(this.categorizePoses.bind(this));
```

2022-08-08 23:17 UTC, ndan029 commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +      this.loadPosesSource(changes.posesByPoseSource.currentValue);
Does this happen on the angular dev server? I had this happen to me and I thought I had fixed it.

2022-08-10 19:31 UTC, supr3m3 commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +      this.loadPosesSource(changes.posesByPoseSource.currentValue);
yeah, i saw the error occurring on the dev server.

2022-09-06 17:18 UTC, ndan029 commented on angular/app/src/app/shared/components/maps/map-instance/map-instance.component.ts
> +    }, this);
Fixed

2022-10-03 21:09 UTC, supr3m3 approved these changes
map changing bug in another PR

2023-03-10 20:37 UTC, closed without merging